### ISSUE TITLE
Different RTL8111F Card

### ISSUE THREAD

**Issue by InvisibleFunction** [swthemathwiz/wyse-5070-ethernet-adapter#1]
Hi I bought a "Mini PCIE Network Card M.2 A+E To RTL8111F Gigabit Ethernet Card Single Port RJ45 Ethernet Network Card" from Aliexpress [here](https://www.aliexpress.us/item/3256803980454538.html)

<details>
  <summary>Specs from the listing</summary>

 Mini PCIE Network Card M.2 A+E To RTL8111F Gigabit Ethernet Card Single Port RJ45 Ethernet Network Card

M.2 A+E RTL8111F Gigabit Ethernet adapter, supports 10/100 / 1000Mbps full-duplex/half-duplex adaptive network.
It supports sending gigabit super long frames, and can provide bidirectional data transmission of up to 1000Mbps.
Use it to implement Gigabit networking to the desktop and improve network performance.
Backwards compatible with 10/100BASE-T systems, so it can easily be plugged into almost any existing network using a CAT-5 cable.
It is suitable for multiple market segments and emerging applications such as desktops, workstations, servers, communication platforms and embedded applications.

product features :
Bus Type: M.2 A/E Key 2230
Integrated 10/100/1000M transceiver
High Performance 1000BASE-T Ethernet Controller Card
Backward compatible with 10/100BASE-T network 10/100/1000Mbps data rate auto-negotiation operation
Compatible with existing CAT-5 UTP cables
Fully compliant with IEEE802.3, IEEE802.3u, IEEE802.3ab
Supports half/full duplex mode and 802.3x flow control
Support IEEE802.1P Layer2 priority encoding
Supports IEEE 802.1Q VLAN tagging
Transmit/receive on-chip buffer support
Supports jumbo frames of 9K bytes
Cross detection and automatic correction operations
Support power down/link power saving
Wake-on-LAN and Remote Wake-up support
Standard and low profile chassis supported
1 RJ45 Gigabit LAN port
Chipset: Realtek RTL8111F
System Requirements:
DOS, Win 7/Win 8/Server 2008/Win 8.1/Server 2012/2016, Win 10 32- 64bit, Linux
There is an available M.2 A+E KEY slot on the motherboard
size:22x30MM
Material:PCB
colour:Green 

![image](https://github.com/swthemathwiz/wyse-5070-ethernet-adapter/assets/3682184/855f8a0c-2295-400e-9008-f1c7b0666399)

</details>

This seems to work fine and shows up in lspci as

```
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 07)
```

I tried to print your Realtek adapter but ran into issues trying to install it. I see the issue you mentioned with 3 display port models where there is no room under the adapter for a screw head. I also see that this Realtek card does look different from the Realteck card you link to. I'll keep playing with it.

I'm letting you know since you said, "I would like to know if there are other working cards." in your readme. Would you like measurements of this board?

**Comment by swthemathwiz** [comment]
@InvisibleFunction  The oneyou sent looks real close to the winyao one I have (without some markings). There are three different models  - two are realtek (my legacy naming error - sorry if that created confusion) . The model you want is 'wyse-winyao-adapter.stl' and the measurements are in 'winyao-nic.scad' if you have a caliper or ruler to check. Also, don't forget to specify 'support placement' -> 'touching buildplate' only. You want to be able to slide the PCB under bumps below the port opening.

**Comment by InvisibleFunction** [comment]
It does measure the same as that winyao one. I'll try that one next, thanks.

**Comment by InvisibleFunction** [comment]
That one worked fine. I don't have a 3d printer so I was dependent on my local library who wasn't sure how to set that support placement setting. There were a ton of supports that I had to clear out, but I got it working eventually! Thanks!

After I got all this working I now see that there's a 2.5G card on aliexpress for $10. It says it has a RTL8125B chipset and sounds interesting.

**Comment by swthemathwiz** [comment]
@InvisibleFunction  :+1:  for local library printing.

I incorporated your changes and also changed the old realtek file names to avoid further confusion. I've seen the RTL8125B too - looks mechanically identical to the  low-profile RTL8111 - but I haven't anything with 2.5G to connect to it!
